name: FreedomChat CI
on: [push, pull_request]
jobs:
  build:
    # Only run on PRs if the source branch is on a different repo. We do not need to run everything twice.
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Build using Gradle
        run: ./gradlew build
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
